pub use self::save_to_amqp::SaveToAmqp;
mod save_to_amqp;
pub use self::save_to_file::SaveToFile;
mod save_to_file;
pub use self::save_to_console::SaveToConsole;
mod save_to_console;
pub use self::save_to_mongodb::SaveToMongoDB;
mod save_to_mongodb;
pub use self::update_progressbar::UpdateProgressBar;
mod update_progressbar;