name: Rust

on:
  push:
    branches: [ main, 0.1.x ]
  pull_request:
    branches: [ main, 0.1.x ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
